-- Add Hero 1 section template to section_templates table

INSERT INTO section_templates (
  name,
  component_path,
  category,
  thumbnail_url,
  description,
  field_schema,
  default_props
) VALUES (
  'Hero 1',
  'sections/hero-1',
  'hero',
  '/placeholder.svg?height=200&width=400',
  'Hero section with badge, headline, subheadline, two CTAs, savings card, and flexible background options (gradient, solid, image, CDN)',
  '{
    "fields": [
      {"name": "badge", "label": "Badge Text", "type": "text", "required": false},
      {"name": "headline", "label": "Headline", "type": "text", "required": true},
      {"name": "subheadline", "label": "Subheadline", "type": "textarea", "required": false},
      {"name": "primaryCTA", "label": "Primary Button Text", "type": "text", "required": false},
      {"name": "primaryCTALink", "label": "Primary Button Link", "type": "url", "required": false},
      {"name": "secondaryCTA", "label": "Secondary Button Text", "type": "text", "required": false},
      {"name": "secondaryCTALink", "label": "Secondary Button Link", "type": "url", "required": false},
      {"name": "disclaimer", "label": "Disclaimer Text", "type": "text", "required": false},
      {"name": "showSavingsCard", "label": "Show Savings Card", "type": "checkbox", "default": true},
      {"name": "savingsTitle", "label": "Savings Card Title", "type": "text", "required": false},
      {"name": "savingsAmount", "label": "Savings Amount", "type": "text", "required": false},
      {"name": "savingsItem1Label", "label": "Savings Item 1 Label", "type": "text", "required": false},
      {"name": "savingsItem1Value", "label": "Savings Item 1 Value", "type": "text", "required": false},
      {"name": "savingsItem2Label", "label": "Savings Item 2 Label", "type": "text", "required": false},
      {"name": "savingsItem2Value", "label": "Savings Item 2 Value", "type": "text", "required": false},
      {"name": "savingsItem3Label", "label": "Savings Item 3 Label", "type": "text", "required": false},
      {"name": "savingsItem3Value", "label": "Savings Item 3 Value", "type": "text", "required": false},
      {"name": "savingsItem4Label", "label": "Savings Item 4 Label", "type": "text", "required": false},
      {"name": "savingsItem4Value", "label": "Savings Item 4 Value", "type": "text", "required": false},
      {"name": "backgroundType", "label": "Background Type", "type": "select", "options": ["solid", "gradient", "image", "cdn"], "default": "gradient"},
      {"name": "backgroundColor", "label": "Background Color", "type": "color", "default": "#f0f9ff"},
      {"name": "gradientStart", "label": "Gradient Start Color", "type": "color", "default": "#f0f9ff"},
      {"name": "gradientEnd", "label": "Gradient End Color", "type": "color", "default": "#e0f2fe"},
      {"name": "gradientDirection", "label": "Gradient Direction", "type": "select", "options": ["to-r", "to-l", "to-t", "to-b", "to-br", "to-bl", "to-tr", "to-tl"], "default": "to-br"},
      {"name": "backgroundImage", "label": "Background Image URL", "type": "url", "required": false},
      {"name": "cdnLink", "label": "CDN Image Link", "type": "url", "required": false}
    ]
  }'::jsonb,
  $json${
    "badge": "$0/month Forever",
    "headline": "Everything missionaries need to raise support",
    "subheadline": "Stop paying $200+/month for multiple tools. Get fundraising pages, email newsletters, CRM, and more — all in one platform for zero monthly fees.",
    "primaryCTA": "Get started — it's free",
    "primaryCTALink": "/auth/signup",
    "secondaryCTA": "See pricing details",
    "secondaryCTALink": "/pricing",
    "disclaimer": "No credit card required • Setup in 5 minutes • Cancel anytime",
    "showSavingsCard": true,
    "savingsTitle": "Annual savings",
    "savingsAmount": "$1,620 - $3,072",
    "savingsItem1Label": "Email newsletters",
    "savingsItem1Value": "$240-600/yr saved",
    "savingsItem2Label": "Fundraising platform",
    "savingsItem2Value": "$588-2,400/yr saved",
    "savingsItem3Label": "CRM & analytics",
    "savingsItem3Value": "Included free",
    "savingsItem4Label": "Payment processing",
    "savingsItem4Value": "Only 3% fee",
    "backgroundType": "gradient",
    "backgroundColor": "#f0f9ff",
    "gradientStart": "#f0f9ff",
    "gradientEnd": "#e0f2fe",
    "gradientDirection": "to-br",
    "backgroundImage": "",
    "cdnLink": ""
  }$json$::jsonb
) ON CONFLICT DO NOTHING;
