import type { SectionConfig } from "../types"

export const heroCenteredConfig: SectionConfig = {
  id: "hero-centered",
  name: "Hero Centered",
  description: "Full-screen centered hero with blur effects, supporting gradient, image, or CDN backgrounds",
  thumbnail: "/hero-centered-preview.jpg",
  category: "hero",
  defaultProps: {
    heading: "Everything missionaries need to raise support",
    subheading:
      "Replace 4+ tools with one platform. Save thousands per year. Built specifically for support-raising missionaries.",
    buttonText: "Get Started Free",
    buttonLink: "/auth/signup",
    buttonStyle: "solid",
    buttonColor: "#FACC15",
    buttonTextColor: "#1a1a1a",
    backgroundType: "gradient",
    backgroundImage: "",
    cdnLink: "",
    gradientStart: "#1e3a5f",
    gradientEnd: "#0f172a",
    gradientDirection: "to bottom",
    overlayColor: "#000000",
    overlayOpacity: 20,
    enableBlur: true,
    blurIntensity: 30,
    textColor: "#ffffff",
    headingFont: "italic-serif",
    minHeight: "100vh",
  },
  fields: [
    { name: "heading", label: "Heading", type: "text" },
    { name: "subheading", label: "Subheading", type: "textarea" },
    { name: "buttonText", label: "Button Text", type: "text" },
    { name: "buttonLink", label: "Button Link", type: "text" },
    { name: "buttonStyle", label: "Button Style", type: "select", options: ["solid", "outline"] },
    { name: "buttonColor", label: "Button Color", type: "color" },
    { name: "buttonTextColor", label: "Button Text Color", type: "color" },
    { name: "backgroundType", label: "Background Type", type: "select", options: ["image", "cdn", "gradient"] },
    { name: "backgroundImage", label: "Background Image URL", type: "text" },
    { name: "cdnLink", label: "CDN Link", type: "text" },
    { name: "gradientStart", label: "Gradient Start Color", type: "color" },
    { name: "gradientEnd", label: "Gradient End Color", type: "color" },
    {
      name: "gradientDirection",
      label: "Gradient Direction",
      type: "select",
      options: ["to bottom", "to top", "to right", "to left", "to bottom right", "to bottom left"],
    },
    { name: "overlayColor", label: "Overlay Color", type: "color" },
    { name: "overlayOpacity", label: "Overlay Opacity (%)", type: "number" },
    { name: "enableBlur", label: "Enable Edge Blur", type: "boolean" },
    { name: "blurIntensity", label: "Blur Intensity (%)", type: "number" },
    { name: "textColor", label: "Text Color", type: "color" },
    { name: "headingFont", label: "Heading Font Style", type: "select", options: ["sans", "serif", "italic-serif"] },
    { name: "minHeight", label: "Minimum Height", type: "text" },
  ],
}
